config/routes.rb
Auctions::Application.routes.draw do
  resources :auctions

  root :to => 'auctions#index'
  match ".json" => 'auctions#index', defaults: { format: :json }

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  attr_accessor :till_the_end
  attr_accessible :name, :end_date, :auction_type_id, :till_the_end

  belongs_to :auction_type

  validates_presence_of :auction_type_id, :end_date
  validate :date_validator

  validates :name, :presence => true,
            :length => {minimum: 2}

  default_scope joins(:auction_type).readonly(false).order('weight ASC, end_date ASC')

  self.per_page = 10

  def date_validator
    errors.add(:end_date, "date cannot be in the past") if end_date && Time.now >= end_date
  end

  def name
    n  = read_attribute(:name)
    case auction_type_id
      when 2 # za grosik -> seed.rb
        '@@' + n.upcase
      when 3 # kup teraz -> seed.rb
        n.upcase + '!!!'
      else n.upcase
    end
  end

  def till_the_end
    Time.now < end_date ? time_ago_in_words(end_date, true) : nil
  end


end

app/models/auction_type.rb
class AuctionType < ActiveRecord::Base
  attr_accessible :name, :weight
  has_many :auctions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def pathx
    request.fullpath
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  def index
    @auctions = Auction.includes(:auction_type).paginate(:page => params[:page])
    respond_to do |format|
      format.html
      format.json { render :json => @auctions.map{ |x| [x.id, x.till_the_end] } }
    end
  end

  def show
    @auction = Auction.find(params[:id])
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(params[:auction])
    if @auction.save
      redirect_to @auction, :notice => "Successfully created auction."
    else
      render :action => 'new'
    end
  end

  def edit
    @auction = Auction.find(params[:id])
  end

  def update
    @auction = Auction.find(params[:id])
    if @auction.update_attributes(params[:auction])
      redirect_to @auction, :notice  => "Successfully updated auction."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @auction = Auction.find(params[:id])
    @auction.destroy
    redirect_to auctions_url, :notice => "Successfully destroyed auction."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
  def json_process(auctions)
    auctions.map{|a| [a.id, a.end_time] }
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/auctions/_form.html.erb
<%= form_for @auction do |f| %>

  <%= f.error_messages %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :auction_type_id %><br />
    <%= f.collection_select :auction_type_id, AuctionType.all, :id, :name  %>
  </div>

  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/auctions/edit.html.erb
<% title "Edit Auction" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @auction %> |
  <%= link_to "View All", auctions_path %>
</p>

app/views/auctions/index.html.erb
<% title "Auctions" %>

<p><%= link_to "New Auction", new_auction_path %></p>

<%= content_tag "table", id: "auctions", data: {url: request.fullpath } do %>
  <tr>
    <th>Name</th>
    <th>End time</th>
    <th>Till the end</th>
    <th>Type</th>
    <th colspan="4">Actions</th>
  </tr>
  <% for auction in @auctions %>
    <tr>
      <td><%= auction.name %></td>
      <td><%= auction.end_date.strftime("%d/%m/%y - %H:%M") %></td>
      <td id="time4auction_<%= auction.id %>"><%= auction.till_the_end ?  auction.till_the_end : '<span class="red">expired</span>'.html_safe %></td>
      <td><%= auction.auction_type.name %></td>
      <td><%= link_to "Show", auction %></td>
      <td><%= link_to "Edit", edit_auction_path(auction) %></td>
      <td><%= link_to "Destroy", auction, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
<% end %>

<br />
<%= will_paginate @auctions %>

app/views/auctions/new.html.erb
<% title "New Auction" %>

<%= render 'form' %>

<p><%= link_to "Back to List", auctions_path %></p>

app/views/auctions/show.html.erb
<% title "Auction" %>

<p>
  <strong>Name:</strong>
  <%= @auction.name %>
</p>
<p>
  <strong>End date:</strong>
  <%= @auction.end_date %>
</p>
<p>
  <strong>Till end date:</strong>
  <%= @auction.end_date > Time.now ? time_ago_in_words(@auction.end_date, true) : 'expired' %>
</p>
<p>
  <strong>Auction type:</strong>
  <%= @auction.auction_type.name  %>
</p>

<p>
  <%= link_to "Edit", edit_auction_path(@auction) %> |
  <%= link_to "Destroy", @auction, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", auctions_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>